# Chapter 8: Pandas for Data Analysis (Core Skills)

**Goal**: Become proficient with Pandas – the single most important library for any data analyst.

Pandas gives you Excel-like power with the speed and flexibility of Python.

---

## 9.1 Creating DataFrames

In [1]:
import pandas as pd
import numpy as np

# From dictionary
data = {
    "Region": ["North", "South", "East", "West", "North", "South"],
    "Month": ["Jan", "Jan", "Jan", "Jan", "Feb", "Feb"],
    "Sales": [1250000, 980000, 1120000, 1450000, 1320000, 1050000],
    "Target": [1200000, 1000000, 1100000, 1400000, 1250000, 1000000]
}

df = pd.DataFrame(data)
df

  Region Month    Sales   Target
0  North   Jan  1250000  1200000
1  South   Jan   980000  1000000
2   East   Jan  1120000  1100000
3   West   Jan  1450000  1400000
4  North   Feb  1320000  1250000
5  South   Feb  1050000  1000000

In [2]:
# Quick exploration
print(df.shape)
print(df.columns.tolist())
print(df.dtypes)
df.head()

(6, 4)
['Region', 'Month', 'Sales', 'Target']
Region      str
Month       str
Sales     int64
Target    int64
dtype: object

  Region Month    Sales   Target
0  North   Jan  1250000  1200000
1  South   Jan   980000  1000000
2   East   Jan  1120000  1100000
3   West   Jan  1450000  1400000
4  North   Feb  1320000  1250000

In [3]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Region  6 non-null      str
 1   Month   6 non-null      str
 2   Sales   6 non-null      int64
 3   Target  6 non-null      int64
dtypes: int64(2), str(2)
memory usage: 324.0 bytes

              Sales        Target
count  6.000000e+00  6.000000e+00
mean   1.195000e+06  1.158333e+06
std    1.769463e+05  1.562583e+05
min    9.800000e+05  1.000000e+06
25%    1.067500e+06  1.025000e+06
50%    1.185000e+06  1.150000e+06
75%    1.302500e+06  1.237500e+06
max    1.450000e+06  1.400000e+06

---

## 9.2 Selecting & Filtering Data

In [4]:
# Column selection
df["Sales"]
df[["Region", "Sales"]]

  Region    Sales
0  North  1250000
1  South   980000
2   East  1120000
3   West  1450000
4  North  1320000
5  South  1050000

In [5]:
# Filtering rows (Boolean indexing)
df[df["Sales"] > 1200000]

  Region Month    Sales   Target
0  North   Jan  1250000  1200000
3   West   Jan  1450000  1400000
4  North   Feb  1320000  1250000

In [6]:
# Multiple conditions
df[(df["Sales"] > 1100000) & (df["Region"] == "West")]

  Region Month    Sales   Target
3   West   Jan  1450000  1400000

In [7]:
# Using .loc and .iloc
df.loc[0:2, ["Region", "Sales"]]     # Label based
df.iloc[0:3, 0:2]                    # Position based

  Region Month
0  North   Jan
1  South   Jan
2   East   Jan

---

## 9.3 Creating New Columns (Feature Engineering)

In [8]:
df["Achievement"] = (df["Sales"] / df["Target"]) * 100
df["Variance"] = df["Sales"] - df["Target"]
df["Status"] = np.where(df["Achievement"] >= 100, "Met", "Missed")
df

  Region Month    Sales   Target  Achievement  Variance  Status
0  North   Jan  1250000  1200000   104.166667     50000     Met
1  South   Jan   980000  1000000    98.000000    -20000  Missed
2   East   Jan  1120000  1100000   101.818182     20000     Met
3   West   Jan  1450000  1400000   103.571429     50000     Met
4  North   Feb  1320000  1250000   105.600000     70000     Met
5  South   Feb  1050000  1000000   105.000000     50000     Met

---

## 9.4 Sorting & Ranking

In [9]:
df.sort_values("Sales", ascending=False)

  Region Month    Sales   Target  Achievement  Variance  Status
3   West   Jan  1450000  1400000   103.571429     50000     Met
4  North   Feb  1320000  1250000   105.600000     70000     Met
0  North   Jan  1250000  1200000   104.166667     50000     Met
2   East   Jan  1120000  1100000   101.818182     20000     Met
5  South   Feb  1050000  1000000   105.000000     50000     Met
1  South   Jan   980000  1000000    98.000000    -20000  Missed

In [10]:
df.sort_values(["Region", "Sales"], ascending=[True, False])

  Region Month    Sales   Target  Achievement  Variance  Status
2   East   Jan  1120000  1100000   101.818182     20000     Met
4  North   Feb  1320000  1250000   105.600000     70000     Met
0  North   Jan  1250000  1200000   104.166667     50000     Met
5  South   Feb  1050000  1000000   105.000000     50000     Met
1  South   Jan   980000  1000000    98.000000    -20000  Missed
3   West   Jan  1450000  1400000   103.571429     50000     Met

---

## 9.5 Aggregation & GroupBy (The Heart of Analysis)

In [11]:
# Total sales by region
df.groupby("Region")["Sales"].sum()

Region
East     1120000
North    2570000
South    2030000
West     1450000
Name: Sales, dtype: int64

In [12]:
# Multiple aggregations
df.groupby("Region").agg({
    "Sales": ["sum", "mean", "max"],
    "Target": "sum",
    "Achievement": "mean"
}).round(1)

          Sales                       Target Achievement
            sum       mean      max      sum        mean
Region
East    1120000  1120000.0  1120000  1100000       101.8
North   2570000  1285000.0  1320000  2450000       104.9
South   2030000  1015000.0  1050000  2000000       101.5
West    1450000  1450000.0  1450000  1400000       103.6

In [13]:
# Pivot table style
pd.pivot_table(df, values="Sales", index="Region", columns="Month", aggfunc="sum", fill_value=0)

Month       Feb      Jan
Region
East          0  1120000
North   1320000  1250000
South   1050000   980000
West          0  1450000

---

## 9.6 Handling Missing Data

In [14]:
# Create sample with missing values
df2 = df.copy()
df2.loc[1, "Sales"] = np.nan
df2.loc[3, "Target"] = np.nan
df2

  Region Month      Sales     Target  Achievement  Variance  Status
0  North   Jan  1250000.0  1200000.0   104.166667     50000     Met
1  South   Jan        NaN  1000000.0    98.000000    -20000  Missed
2   East   Jan  1120000.0  1100000.0   101.818182     20000     Met
3   West   Jan  1450000.0        NaN   103.571429     50000     Met
4  North   Feb  1320000.0  1250000.0   105.600000     70000     Met
5  South   Feb  1050000.0  1000000.0   105.000000     50000     Met

In [15]:
print(df2.isna().sum())

# Drop rows with any NaN
df2.dropna()

# Fill with mean / median / specific value
df2["Sales"].fillna(df2["Sales"].mean(), inplace=False)

Region         0
Month          0
Sales          1
Target         1
Achievement    0
Variance       0
Status         0
dtype: int64

0    1250000.0
1    1238000.0
2    1120000.0
3    1450000.0
4    1320000.0
5    1050000.0
Name: Sales, dtype: float64

---

## 9.7 Reading Real Files (CSV & Excel)

In [16]:
# Most common way you will load data
# df = pd.read_csv("sales_data.csv")
# df = pd.read_excel("sales_data.xlsx", sheet_name="Sheet1")

# Quick demo – save and reload
df.to_csv("temp_sales.csv", index=False)
df_reloaded = pd.read_csv("temp_sales.csv")
df_reloaded.head()

  Region Month    Sales   Target  Achievement  Variance  Status
0  North   Jan  1250000  1200000   104.166667     50000     Met
1  South   Jan   980000  1000000    98.000000    -20000  Missed
2   East   Jan  1120000  1100000   101.818182     20000     Met
3   West   Jan  1450000  1400000   103.571429     50000     Met
4  North   Feb  1320000  1250000   105.600000     70000     Met

---

## 9.8 Merging DataFrames (Joins)

In [17]:
region_info = pd.DataFrame({
    "Region": ["North", "South", "East", "West"],
    "Manager": ["Anita", "Ravi", "Priya", "Vikram"],
    "Zone": ["A", "B", "A", "B"]
})

merged = pd.merge(df, region_info, on="Region", how="left")
merged

  Region Month    Sales   Target  Achievement  Variance  Status Manager Zone
0  North   Jan  1250000  1200000   104.166667     50000     Met   Anita    A
1  South   Jan   980000  1000000    98.000000    -20000  Missed    Ravi    B
2   East   Jan  1120000  1100000   101.818182     20000     Met   Priya    A
3   West   Jan  1450000  1400000   103.571429     50000     Met  Vikram    B
4  North   Feb  1320000  1250000   105.600000     70000     Met   Anita    A
5  South   Feb  1050000  1000000   105.000000     50000     Met    Ravi    B

---

## Business Challenge – Chapter 8

Create a realistic sales dataset (at least 12 rows) with columns:  
`Date, Region, Product, Units, Unit_Price`

Then perform:
1. Calculate Revenue = Units × Unit_Price
2. Find total revenue by Region and by Product
3. Identify the top product by revenue
4. Calculate average selling price by region
5. Create a Status column: “High” if Revenue > 500000 else “Normal”
6. Export the final DataFrame to a CSV file

In [18]:
# Your solution here
import pandas as pd
import numpy as np

---

## Key Takeaways
- DataFrame is your new Excel sheet – but far more powerful.
- `groupby` + `agg` is the core of almost every business analysis.
- Always explore with `.head()`, `.info()`, `.describe()` first.
- Clean missing values early.

**Next Chapter**: Data Visualization – Turning Numbers into Stories